### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by albertosaurio65** [1mphuls3/CreateCafe-1.16-#2]
While translating and testing the mod I have found these errors

- some liquids appear like this
![bug1](https://user-images.githubusercontent.com/70109413/155777837-9f9968fc-ef3b-4420-aa13-0a79a1b2241e.png)

- The oreo half has no texture

![bug2](https://user-images.githubusercontent.com/70109413/155777864-9f680194-8e80-4b12-b7f6-5a2140af6c2a.png)
 
- the 2 berries that the mod adds cannot be planted in the ground like the sweet berries in the base game
- obtaining cassava and other things ( blood_orange, mana_barries, coffee_fruit... )ooo remains a mystery, the JEI does not show where they are obtained, nor does the [JER ](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)

For the rest everything is great and I'm waiting for 1.18! I'll post the translation in a bit

**Comment by albertosaurio65** [comment]
when I put the filling in half of the oreo, the final oreo is made without having to put another half on top

**Comment by 1mphuls3** [comment]
Sorry for the late response. The two fruits aren't meant to be planted, they are meant to be made to encourage automation rather than just plant farms for them. 
Mana Berries require Botania to be installed, and the Blood Orange requires Blood Magic. 
Those two should show in JEI with those mods installed. As for the cassava and coffee fruit, Ill see if I can get the drops to show in JER. They both can be obtained by planting their corresponding seeds.
Currently Coffee Fruit and Beans have no uses other than just eating them, I am probably going to work on the 1.18 port and add coffee for 1.18. Then I'll think about back porting that to 1.16.

**Comment by 1mphuls3** [comment]
I fixed all but the JER issue. I am unsure how to fix that considering JER has no wiki on how to add my own entries, the crops are both using the almost exactly the same code as vanilla, besides the seed item and hitbox, so I don't know why it doesn't work.

**Comment by albertosaurio65** [comment]
okey, thanks for answering
